<a href="https://colab.research.google.com/github/Tushar3087/ML-Lab/blob/main/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Create a Python list
my_list = [10, 20, 30, 40, 50]

# Convert list to NumPy array
arr = np.array(my_list)

# Display the array
print("NumPy Array:", arr)

# Print shape of array
print("Shape of array:", arr.shape)

# Print data type of array
print("Data type of array:", arr.dtype)

NumPy Array: [10 20 30 40 50]
Shape of array: (5,)
Data type of array: int64


In [2]:
import numpy as np

# Create a 3x4 matrix of zeros
zeros_matrix = np.zeros((3, 4))

# Create a 2x5 matrix of ones
ones_matrix = np.ones((2, 5))

# Print matrices
print("3x4 Zero Matrix:\n", zeros_matrix)
print("Shape:", zeros_matrix.shape)

print("\n2x5 Ones Matrix:\n", ones_matrix)
print("Shape:", ones_matrix.shape)

3x4 Zero Matrix:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape: (3, 4)

2x5 Ones Matrix:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Shape: (2, 5)


In [3]:
import numpy as np

# Create array from 1 to 12
arr = np.arange(1, 13)

# Reshape into 3x4 matrix
reshaped_arr = arr.reshape(3, 4)

# Display original array
print("Original Array:")
print(arr)
print("Shape:", arr.shape)

# Display reshaped array
print("\nReshaped Array (3x4):")
print(reshaped_arr)
print("Shape:", reshaped_arr.shape)

Original Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Shape: (12,)

Reshaped Array (3x4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)


In [4]:
import numpy as np

# Create an array of 10 random integers (between 1 and 100)
arr = np.random.randint(1, 101, 10)

# Display the array
print("Random Array:", arr)

# Find minimum, maximum, mean, and sum
print("Minimum value:", np.min(arr))
print("Maximum value:", np.max(arr))
print("Mean value:", np.mean(arr))
print("Sum of elements:", np.sum(arr))

Random Array: [54 92  9 23 53 99 36 21 98 12]
Minimum value: 9
Maximum value: 99
Mean value: 49.7
Sum of elements: 497


In [5]:
import pandas as pd

# Create a dictionary
data = {
    "Name": ["Tushar", "Anusha", "Parin", "Rahul"],
    "Marks": [85, 92, 78, 88]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print("DataFrame:\n")
print(df)

# Print data types of each column
print("\nData Types:\n")
print(df.dtypes)


DataFrame:

     Name  Marks
0  Tushar     85
1  Anusha     92
2   Parin     78
3   Rahul     88

Data Types:

Name     object
Marks     int64
dtype: object
