<a href="https://colab.research.google.com/github/Tushar3087/ML-Lab/blob/main/Lab9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Import required libraries
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder, StandardScaler


# Load dataset (make sure Iris.csv is uploaded)
data = pd.read_csv("Iris.csv")

# Drop 'Id' column if present
if 'Id' in data.columns:
    data = data.drop('Id', axis=1)

# Rename columns (to match standard format)
data.columns = [
    "sepal_length",
    "sepal_width",
    "petal_length",
    "petal_width",
    "species"
]

# Remove any missing values
data = data.dropna()

# Features and target
X = data.iloc[:, 0:4].values
y = data.iloc[:, 4].values

# Convert species labels to numeric values
encoder = LabelEncoder()
y = encoder.fit_transform(y)

# Feature scaling (important for ANN)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Create ANN model (MLP)
model = MLPClassifier(hidden_layer_sizes=(10, 8), max_iter=1000, random_state=42)

# Train model
model.fit(X_train, y_train)

# Prediction
y_pred = model.predict(X_test)

# Evaluation
print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 1.0

Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

